version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiktok-downloader
    image: ghcr.io/jag-k/tiktok-downloader:latest
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ./data:/data

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=video-downloader # database name you want to make
      - MONGO_INITDB_ROOT_USERNAME=root # set your container root username
      - MONGO_INITDB_ROOT_PASSWORD=root # set vour container root password
    ports:
      - "27017:27017"
    volumes:
      - ./config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongo:/data/db
    tty: true
    stdin_open: true

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - $HOME/.docker/config.json:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command: --cleanup --interval 300
