# This file is generated by cli/commands.py
# Do not edit this file directly
# Run `poetry run -- python -m cli generate_makefile` to update this file

compile_locale:  # Extract strings from code to .POT file
	poetry run -- python -m cli compile_locale

extract_locale:  # Update .PO file for Russian language
	poetry run -- python -m cli extract_locale -l ru

update_locale:  # Extract strings and update .PO file for Russian language
	poetry run -- python -m cli update_locale -l ru

full_update_locale:  # Compile .PO files to .MO files
	poetry run -- python -m cli full_update_locale

generate_notify_schema:  # Generate schema for notify.json file
	poetry run -- python -m cli generate_notify_schema

generate_notify_md:  # Generate markdown for notify.json file
	poetry run -- python -m cli generate_notify_md

generate_makefile:  # Generate Makefile
	poetry run -- python -m cli generate_makefile

generate_makefile_md:  # Generate Makefile and update README.md
	poetry run -- python -m cli generate_makefile_md

full_update_readme:  # Full update README.md
	poetry run -- python -m cli full_update_readme
